### ISSUE TITLE
iptorrents manual search error: 

### ISSUE THREAD

**Issue by dci2112** [SickChill/sickchill.github.io#16]
I just manually upgraded to the latest version to get the cloudflare fix. Now manual searches on iptorrents are not working for another reason:

TypeError: tuple indices must be integers, not str

`
2019-04-10 00:25:47 INFO SEARCHQUEUE-MANUAL-340959 :: Unable to find a download for: [Killing Eve - S02E01 - Do You Know How to Dispose of a Body] 2019-04-10 00:25:47 DEBUG SEARCHQUEUE-MANUAL-340959 :: formatting pattern: %SN - S%0SE%0E - %EN -> Killing Eve - S02E01 - Do You Know How to Dispose of a Body 2019-04-10 00:25:47 DEBUG SEARCHQUEUE-MANUAL-340959 :: formatting pattern: %SN - S%0SE%0E - %EN -> Killing Eve - S02E01 - Do You Know How to Dispose of a Body 2019-04-10 00:25:47 INFO SEARCHQUEUE-MANUAL-340959 :: [IPTorrents] :: No NZB/Torrent providers found or enabled in the sickchill config for backlog searches. Please check your settings. AA TypeError: tuple indices must be integers, not str AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message] AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1522, in get_level AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error)) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1578, in handle_requests_exception AA handle_requests_exception(error) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1465, in getURL AA return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickchill/providers/GenericProvider.py", line 372, in get_url AA self.get_url(login_url, returns='text') AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/providers/iptorrents.py", line 83, in login AA if not self.login(): AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/providers/iptorrents.py", line 108, in search AA items_list += self.search(search_string, ep_obj=episode) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickchill/providers/GenericProvider.py", line 170, in find_search_results AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/search.py", line 474, in searchProviders 2019-04-10 00:25:47 DEBUG SEARCHQUEUE-MANUAL-340959 :: [IPTorrents] :: Traceback (most recent call last): AA TypeError: tuple indices must be integers, not str AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message] AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1522, in get_level AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error)) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1578, in handle_requests_exception AA handle_requests_exception(error) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1465, in getURL AA return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickchill/providers/GenericProvider.py", line 372, in get_url AA self.get_url(login_url, returns='text') AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/providers/iptorrents.py", line 83, in login AA if not self.login(): AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/providers/iptorrents.py", line 108, in search AA items_list += self.search(search_string, ep_obj=episode) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickchill/providers/GenericProvider.py", line 170, in find_search_results AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality) AA File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/search.py", line 474, in searchProviders AA Traceback (most recent call last):
`

**Comment by eldite** [comment]
I am experiencing this also.

**Comment by eldite** [comment]
Looks like it's this: https://github.com/SickChill/SickChill/issues/5420

I used the init.py update fix. 

just gets you further down the road, on to the next issue...

**Comment by Hoveys** [comment]
So i have it installed on Win10.... i'm not sure how to update the file, anyone provide any guidance?

**Comment by miigotu** [comment]
This is the wrong location for issues. This is the repo for the site and scene exceptions. I will be merging to master shortly and you can try the new update then.
